remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Insta Insight]
description: [A portfolio site focused on illustrating the integration of advanced data structures and algorithms in Instagramâ€™s ecosystem.]
